###Consultar todos los estudiantes
GET http://127.0.0.1:8000/api/app/estudiantes



###Crear un estudiante
POST http://127.0.0.1:8000/api/app/estudiante
Content-Type: application/json
{
    "nombre": "Carlos Pérez",
    "email": "carlos@test.com",
    "telefono": "123456789"
}



###Consultar un estudiante por ID
GET http://127.0.0.1:8000/api/app/estudiante/{id}



###Actualizar un estudiante
PUT http://127.0.0.1:8000/api/app/estudiante/{id}
Content-Type: application/json
{
    "nombre": "Carlos Gómez",
    "email": "carlosgomez@test.com",
    "telefono": "987654321"
}



###Eliminar un estudiante
DELETE http://127.0.0.1:8000/api/app/estudiante/{id}



###Listar estudiantes aprobados
GET http://127.0.0.1:8000/api/app/estudiantes-aprobados



###Listar estudiantes reprobados
GET http://127.0.0.1:8000/api/app/estudiantes-reprobados



###Consultar todas las notas
GET http://127.0.0.1:8000/api/app/notas



###Crear una nota
POST http://127.0.0.1:8000/api/app/nota
Content-Type: application/json
{
    "id_estudiante": 1,
    "asignatura": "Matemáticas",
    "nota": 4.5
}



###Consultar una nota por ID
GET http://127.0.0.1:8000/api/app/nota/{id}



###Actualizar una nota
PUT http://127.0.0.1:8000/api/app/nota/{id}
Content-Type: application/json
{
    "id_estudiante": 1,
    "asignatura": "Física",
    "nota": 3.8
}



###Eliminar una nota
DELETE http://127.0.0.1:8000/api/app/nota/{id}
